### ISSUE TITLE
ERR_PROXY_CONNECTION_FAILED

### ISSUE THREAD

**Issue by 80sCyberMan** [LukeProducts/only-working-YouTube-View-Bot-by-LZ#1]
bot worked fine for a day, even gave some decent views, now for the last 2 days when I boot it up I get the error:

raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_PROXY_CONNECTION_FAILED (Session info: chrome=87.0.4280.66)

Is there a way of fixing this?

**Comment by zkenstein** [comment]
Same here

`selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_PROXY_CONNECTION_FAILED`

**Comment by onix010** [comment]
I got the error fixed.  On Chrome when the ERR_PROXY_CONNECTION_FAILED appears click on the top right there is a blue x. Click on it and then click change identity. Once identity is changed click on the refresh button on chrome (or F5). It should continue with out stopping.

**Comment by onix010** [comment]
I got it to work. I managed to figure to bypass the error.

**Comment by zkenstein** [comment]
> I got it to work. I managed to figure to bypass the error.

Nice, thanks for the clue

**Comment by onix010** [comment]
Did you fix it? Or you need help??

**Comment by onix010** [comment]
The views don't go up by much. like in 14 hours i got like 150 views only.

**Comment by LukeProducts** [comment]
that's a problem, you're right.
I have made a new program with proxies that you can run directly in threads.
This should speed up the process:
https://github.com/LukeProducts/Viewer-2.0
warm greetings 
Luke Z

**Comment by onix010** [comment]
Awesome thank you
