### ISSUE TITLE
i'm getting these errors, can you fix it ?

### ISSUE THREAD

**Issue by new2gi** [LukeProducts/only-working-YouTube-View-Bot-by-LZ#3]
![Screenshot (17)](https://user-images.githubusercontent.com/80427293/110698750-10569a80-8214-11eb-8ca0-e92ebc62e2ad.png)
![Screenshot (16)](https://user-images.githubusercontent.com/80427293/110698754-10ef3100-8214-11eb-8da6-dbee35bbf447.png)
![Screenshot (15)](https://user-images.githubusercontent.com/80427293/110698755-1187c780-8214-11eb-9ec9-9aa4050ad847.png)
![Screenshot (14)](https://user-images.githubusercontent.com/80427293/110698757-12205e00-8214-11eb-82a0-7f8b651180de.png)
![Screenshot (13)](https://user-images.githubusercontent.com/80427293/110698761-12b8f480-8214-11eb-845d-c72fe2f91ed7.png)
![Screenshot (12)](https://user-images.githubusercontent.com/80427293/110698762-12b8f480-8214-11eb-9a6b-c68490ab6787.png)
![Screenshot (11)](https://user-images.githubusercontent.com/80427293/110698765-13518b00-8214-11eb-91f5-a31fb98577c9.png)
![Screenshot (10)](https://user-images.githubusercontent.com/80427293/110698766-13518b00-8214-11eb-8a01-e59acf0bbc1e.png)

**Comment by LukeProducts** [comment]
I think you used too many threads and your pc could not handle so many fenter.
Try to use less threads and call more, or use the new and professional version:
https://github.com/LukeProducts/YouTubeViewer-2.0
I have added a watn hint for threads but also inst old program.

With kind regards

LukeProducts

**Comment by new2gi** [comment]
thank you sir
