### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by ImKill6r** [LukeProducts/only-working-YouTube-View-Bot-by-LZ#5]
Recibo este error como podria solucionar?
![232323](https://user-images.githubusercontent.com/76989969/123026320-8f29aa80-d3a1-11eb-9abd-94d0fe0d9103.png)

**Comment by LukeProducts** [comment]
You have a different default installation for the Chrome driver and need to replace the chromedriver.exe file with the version of chromedriver.exe that your PC supports.
The downloads for this can be found at https://chromedriver.chromium.org/downloads

With kind regards

LukeProducts
